
language: cpp

branches:
  except: /pr\/.*/

script:
  - find / -name "*gtest*"
  - ./reconf
  - mkdir build && cd build && ../configure && make -j && make check
  

#before_install:
#  - sudo apt-get -qq update
#  - sudo apt-get install -y libgtest-dev

install:
  - export CXX="$COMPILER"
  - export CC=`echo $COMPILER | sed -e 's/^g++/gcc/' -e 's/^clang++/clang/'`

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libgtest-dev
      env:
        - COMPILER=g++-6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang++-3.7
            - libgtest-dev
      env:
        - COMPILER=clang++-3.7

notifications:
  email: false

