language: generic
os: linux
dist: trusty

branches:
  only:
    - master

script:
  - mkdir build
  - cd build
  - cmake -DWITH_EX=false .. && make -j check
  - cmake -DWITH_EX=true .. && make -j check
  
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgtest-dev
  # what a nice bug wasted 3 hours of my life...
  - (mkdir -p /tmp/gtest && cd /tmp/gtest && cmake -DCMAKE_BUILD_TYPE=RELEASE /usr/src/gtest && make && sudo mv libg* /usr/lib/)

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - CXX=g++-7

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8']
      env:
        - CXX=g++-8

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
          packages: ['g++-8', 'clang-6.0']
      env:
        - CXX=clang++-6.0

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - CXX=g++-7
        - BUILD_FLAGS="-g -O0"
        - CXXFLAGS="--coverage"
      before_install:
        - pip install --user cpp-coveralls
        - sudo apt-get -qq update
        - sudo apt-get install -y libgtest-dev
        - (mkdir -p /tmp/gtest && cd /tmp/gtest && cmake -DCMAKE_BUILD_TYPE=RELEASE /usr/src/gtest && make && sudo mv libg* /usr/lib/)
      script:
        - cmake . && make VERBOSE=1 -j check
      after_success:
        - coveralls --verbose --exclude-pattern '.*/CMakeFiles/.*' --gcov gcov-7 --gcov-options '\-lp'

notifications:
  email: false

