language: generic
os: linux
dist: xenial

script:
  - mkdir build && cd build
  - cmake ..
  - make -j
  - ./gtest_med
  
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgtest-dev
  # what a nice bug wasted 3 hours of my life...
  - (mkdir -p /tmp/gtest && cd /tmp/gtest && cmake -DCMAKE_BUILD_TYPE=RELEASE /usr/src/gtest && make && sudo mv libg* /usr/lib/)

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - CXX=g++-7

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8']
      env:
        - CXX=g++-8

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-9']
      env:
        - CXX=g++-9


    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-6']
          packages: ['clang-6.0', 'g++-8']
      env:
        - CXX=clang++-6.0

    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages: ['clang-9', 'g++-9']
      env:
        - CXX=clang++-9

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - CXX=g++-7
      before_install:
        - pip install --user cpp-coveralls
        - sudo apt-get -qq update
        - sudo apt-get install -y libgtest-dev
        - (mkdir -p /tmp/gtest && cd /tmp/gtest && cmake -DCMAKE_BUILD_TYPE=RELEASE /usr/src/gtest && make && sudo mv libg* /usr/lib/)
      script:
        - mkdir build && cd build
        - cmake -DCOVERAGE=ON ..
        - make VERBOSE=1 -j check
        - cd ..
      after_success:
        - coveralls
          --root .
          --build-root ./build
          --exclude-pattern 'build/CMakeFiles/(\d+.*|.*\.(c|cxx)$)'
          --exclude benchmark
          --gcov gcov-7
          --gcov-options '\--long-file-names --preserve-paths'
          --verbose

notifications:
  email: false


