
language: cpp

branches:
  except: /pr\/.*/

script:
  - ./reconf
  - mkdir build && cd build && ../configure && make -j && make check
  

#before_install:
#  - sudo apt-get -qq update
#  - sudo apt-get install -y libgtest-dev

addons:
  apt:
    packages:
    - libgtest-dev

install:
  - export CXX="$COMPILER"
  - export CC=`echo $COMPILER | sed 's/++//'`

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - COMPILER=g++-6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang++-3.7
      env:
        - COMPILER=clang++-3.7

notifications:
  email: false

