name: Linux

on: [push, pull_request]

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - g++-9
        build_type: [Debug, Release]

    runs-on: ubuntu-latest

    env:
      CXX: ${{ matrix.compiler }}

    steps:
    - run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.compiler }}
        sudo apt-get install -y libgtest-dev
        mkdir ~/gtbuild
        cd ~/gtbuild
        cmake /usr/src/googletest/googletest
    - uses: actions/checkout@v2
    - run: cmake -E make_directory build
    - working-directory: build/
      run: |
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        cmake --build .
        ctest --output-on-failure


